# Github Actions Workflow file that builds and pushes the docker images.
name: pick-bazar-app-prod
env:
  FRONTEND_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/pick-bazar-frontend"
  LARAVEL_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/pick-bazar-laravel"

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "!**/README.md"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!**/README.md"

# Job declaration starts.
jobs:
  react-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache: 'npm'
          cache-dependency-path: 'src/frontend/package-lock.json'
      - name: Install Node Dependencies
        run:
          cd src/frontend && npm ci
        env:
          CI: TRUE
      - name: Test Code Linting
        run: 
          cd src/frontend && npm run lint
      - name: Save Code Linting Report JSON
        run: 
          cd src/frontend && npm run lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "src/frontend/eslint_report.json"
          fail-on-error: false

  laravel-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: "Test Laravel Code"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          pintVersion: 1.2.1
        continue-on-error: true

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: [react-test]
    if: github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and tag the image with git sha and latest.
      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_TAG }}:${{ github.sha }}
            ${{ env.FRONTEND_TAG }}:latest
          cache-from: type=registry,ref=${{ env.FRONTEND_TAG }}:latest
          cache-to: type=inline

      - name: Build and push Docker image for laravel
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./src/api
          file: ./src/api/Dockerfile
          push: true
          tags: |
            ${{ env.LARAVEL_TAG }}:${{ github.sha }}
            ${{ env.LARAVEL_TAG }}:latest
          cache-from: type=registry,ref=${{ env.LARAVEL_TAG }}:latest
          cache-to: type=inline

      # Update the image SHA tag in the deployment file.
      - name: Update the image tag in app.tf terraform file
        run: |
          sed -i "s|image = \"${{ env.FRONTEND_TAG }}:.*\"|image = \"${{ env.FRONTEND_TAG }}:${{ github.sha }}\"|g" infra/app.tf
          sed -i "s|image = \"${{ env.LARAVEL_TAG }}:.*\"|image = \"${{ env.LARAVEL_TAG }}:${{ github.sha }}\"|g" infra/app.tf
      
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            infra:
              - 'infra/**'
            readme:
              - 'infra/**/README.md'
              - 'infra/README.md
      
      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Pick Bazar Bot"
          author_email: "quanganhdb2510@gmail.com"
          message: "BOT: Update the images' tags in app.tf [skip ci]"
          add: "infra/app.tf"

      - name: Run infra-prod workflow
        if : (steps.filter.outputs.infra == 'true' && steps.filter.outputs.readme != 'true') == false
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: infra-prod.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"sha": "${{ github.sha }}"}'